#开发环境配置数据源指向不同机器IP
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/om_member?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: admin
      #oracle配置
      # driverClassName: oracle.jdbc.OracleDriver
      # url: jdbc:oracle:thin:@xx.xx.xx.xx:1521:xe
      # username: fnyg
      # password: 123456
      #SQLServer配置
      # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      # url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
      # username: sa
      # password: 123456